import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rawUrl = process.env.SITE_URL || process.env.CF_PAGES_URL || 'https://albasotokaporta.pages.dev';
const url = new URL(rawUrl);
if (!['https:', 'http:'].includes(url.protocol)) throw new Error('SITE_URL must be an HTTP(S) URL');
url.search = ''; url.hash = ''; url.pathname = url.pathname.replace(/\/$/, '') + '/';
const base = url.href;
const preview = !!process.env.CF_PAGES_URL && (!process.env.SITE_URL || (process.env.CF_PAGES_BRANCH && process.env.CF_PAGES_BRANCH !== (process.env.PRODUCTION_BRANCH || 'main')));
const indexPath = path.join(root, 'dist/index.html');
let html = fs.readFileSync(indexPath, 'utf8').replace(/<meta name="robots" content="noindex,nofollow">\n?/g, '');
html = html.replace(/(<link rel="canonical" href=")[^"]+(">)/, `$1${base}$2`);
html = html.replace(/(<meta property="og:url" content=")[^"]+(">)/, `$1${base}$2`);
html = html.replace(/(<meta property="og:image" content=")[^"]+(">)/, `$1${base}assets/is-05.webp$2`);
html = html.replace(/(<script type="application\/ld\+json" id="business-schema">)([\s\S]*?)(<\/script>)/, (_match, start, data, end) => {const schema=JSON.parse(data);schema.url=base;schema.image=base+'assets/is-05.webp';return start+JSON.stringify(schema)+end;});
if (preview) html = html.replace('</head>', '<meta name="robots" content="noindex,nofollow">\n</head>');
fs.writeFileSync(indexPath, html);
fs.writeFileSync(path.join(root, 'dist/robots.txt'), preview ? 'User-agent: *\nDisallow: /\n' : `User-agent: *\nAllow: /\nSitemap: ${base}sitemap.xml\n`);
fs.writeFileSync(path.join(root, 'dist/sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base.replaceAll('&','&amp;')}</loc></url></urlset>\n`);
console.log('SEO files configured for', base, preview ? '(preview: noindex)' : '(production)');
